### ISSUE TITLE
Should ReactiveSeq.retry count include the initial function call?

### ISSUE THREAD

**Issue by jijisv** [aol/cyclops-react#516]
Passing retry count as 0 to `retry` method is throwing null pointer exception.

Sample code
```java
final AtomicInteger counter = new AtomicInteger(0);
Function<Integer, Integer> fn = i -> counter.incrementAndGet() > 1 ? 2 * i : i / (i -1);

int result = ReactiveSeq.of(1)
                        .retry(fn, 0, 1, TimeUnit.SECONDS)
                        .firstValue();

assertEquals(2, result);
```
Exception:
```java
java.lang.NullPointerException
	at com.aol.cyclops2.util.ExceptionSoftener.uncheck(ExceptionSoftener.java:881)
	at com.aol.cyclops2.util.ExceptionSoftener.throwSoftenedException(ExceptionSoftener.java:851)
	at cyclops.stream.ReactiveSeq.lambda$retry$96(ReactiveSeq.java:3892)
	at com.aol.cyclops2.internal.stream.spliterators.MappingSpliterator.lambda$tryAdvance$1(MappingSpliterator.java:42)
	at com.aol.cyclops2.internal.stream.spliterators.SingleSpliterator.tryAdvance(SingleSpliterator.java:35)
	at com.aol.cyclops2.internal.stream.spliterators.MappingSpliterator.tryAdvance(MappingSpliterator.java:41)
	at com.aol.cyclops2.internal.stream.SpliteratorBasedStream.findFirst(SpliteratorBasedStream.java:309)
	at com.aol.cyclops2.internal.stream.BaseExtendedStream.firstValue(BaseExtendedStream.java:480)
	at com.aol.cyclops2.control.ReactiveSeqTest.retryThrowsNPEIfRetryIsZero(ReactiveSeqTest.java:817)
```
The retry function was not executed in this case and `ExceptionSoftener` is trying to re-throw a null Exception object and thats the reason for the null pointer.

My assumption was that `retry` count is the maximum number of retries to do if the original invocation fails before reporting the error to the caller - means if retry count is 5, then a max 6 calls (original call + 5 retries) before the retry logic report the error. But it seems like it is making only 5 calls (the original call is also inside the retry count) - Is this expected?

**Comment by johnmcclean-aol** [comment]
I can see where you are coming from. It might be more intuitive that way, or could be documented and variables named better. 

Any idea what approach they take in other libraries?

**Comment by jijisv** [comment]
[spring-retry ](https://github.com/spring-projects/spring-retry) has declarative retry support through annotations. As per their documentation the retries (they call `maxAttepts`) is separate from original call.

Another thing I noticed with ReactiveSeq.retry is that the sleep is before the actual function invocation. So if we configure the retry with a 5 min delay, then the retry will wait for 5 min before even making the first call.

**Comment by johnmcclean-aol** [comment]
@jijisv Did we complete this one?

**Comment by jijisv** [comment]
yes. we did.
